name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  http: ^0.13.5
  geolocator: ^9.0.2
  intl: ^0.18.1
  dartz: ^0.10.1
  get_it: ^8.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^2.4.5
  bloc_test: ^9.1.4
  mockito: ^5.4.2

flutter:
  uses-material-design: true
